### ISSUE TITLE
Wrong autoload order

### ISSUE THREAD

**Issue by univeous** [Shiva-Shadowsong/loggie#16]
I'm not sure if this is a Godot issue or a Loggie issue;

But every time I open my project, the autoload order of Loggie shifts to the middle of many of my autoloads, which makes the autoloads before it unable to use Loggie;

Every time I open the project, I have to manually adjust the order of Loggie to the front in order to run my project. (And the order will be reset when the project is opened next time)

Do you have any ideas?

**Comment by Shiva-Shadowsong** [comment]
I'm not able to reproduce it on Godot 4.3. I'll go into the steps below, but the obvious cause for something like this would be this:

In `plugin.gd` -> `_enter_tree()` the method `add_autoload_singleton` is used to add Loggie to your autoloads list.
Any time you re-run Godot and the plugin enters the tree for the first time, this will execute, however for me that doesn't seem to have any effect if I already have the plugin in my autoload list.

In `_disable_plugin`, there is a call to `remove_autoload_singleton` of course, but this will get called only if you disable the plugin, causing `add_autoload_singleton` on next `_enter_tree()` to re-add Loggie and therefore add it as the newest entry on the list.

There might be a way to enforce Loggie to always get added as the first entry in that list, but I'd have to look into it.

Here's me trying to reproduce it with a fresh installation:
https://www.youtube.com/watch?v=e-zEDLo-hHM

After closing Godot and reopening the project, Loggie still stayed in the same place in the autoload order.

Which version of Godot are you using? Maybe that could be relevant.

**Comment by univeous** [comment]
I found it!

This is because I used [godot-global-project](https://github.com/dugramen/godot-global-project), and the script it injected into editor settings  somehow messed up the autoload order. Everything works fine after I cleaned up the related script. Sorry to have taken up your time!

**Comment by Shiva-Shadowsong** [comment]
Ahh, I see! Makes sense.
No problem, glad you figured it out.
