### ISSUE TITLE
Strip non-asset folders from distributed ZIP file

### ISSUE THREAD

**Issue by derkork** [Shiva-Shadowsong/loggie#8]
When you install the addon through the asset library, there are a lof of folders installed that are not needed for running the addon (e.g. `docs` , `screenshots`, `test`, `README.md` ,`LICENSE`:

![image](https://github.com/user-attachments/assets/1852c4f7-bd96-4e53-a1cb-75858a91114a)

It is possible to strip these folders from the ZIP that the asset library is downloading by adding some lines to your `.gitattributes` file. See https://github.com/derkork/godot-statecharts/blob/main/.gitattributes for an example. This would avoid littering other projects with files they don't need to run the logging part.

**Comment by Shiva-Shadowsong** [comment]
I wasn't aware that this was possible via .gitattributes, which I can .gitattribute to my failure to spot the entire "Recommendations" section [here](https://docs.godotengine.org/en/stable/community/asset_library/submitting_to_assetlib.html#recommendations). 

I will use this information to make improvements for the next patch. Thanks for pointing it out!
